# permissions for end users to view compositesecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compositesecret-viewer-role
rules:
- apiGroups:
  - composite.shadowblip.com
  resources:
  - compositesecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - composite.shadowblip.com
  resources:
  - compositesecrets/status
  verbs:
  - get
