# permissions for end users to edit compositesecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compositesecret-editor-role
rules:
- apiGroups:
  - composite.shadowblip.com
  resources:
  - compositesecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - composite.shadowblip.com
  resources:
  - compositesecrets/status
  verbs:
  - get
