---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - composite.shadowblip.com
  resources:
  - compositesecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - composite.shadowblip.com
  resources:
  - compositesecrets/finalizers
  verbs:
  - updatea
- apiGroups:
  - composite.shadowblip.com
  resources:
  - compositesecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
