---
apiVersion: v1
kind: Secret
metadata:
  name: compositesecret-sample-source
stringData:
  mykey: Hello World
---
apiVersion: composite.shadowblip.com/v1alpha1
kind: CompositeSecret
metadata:
  name: compositesecret-sample
spec:
  replacements:
    REPLACEME:
      secretRef:
        name: compositesecret-sample-source
        namespace: default
        key: mykey
  template:
    stringData:
      my-thing: |
        Here we say REPLACEME
