name: Release
on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: 0.0.1
          IMG_NAME: ghcr.io/shadowapex/composite-secrets-controller
        run: make release
